services:
  - type: web
    name: deepfakeshield
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn deepfakeshield.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0