# Generated by Django 4.2.7 on 2026-03-09 14:55

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=core.models.upload_video_path)),
                ('original_filename', models.CharField(default='unknown', max_length=255)),
                ('authenticity_score', models.FloatField(default=0.0)),
                ('classification', models.CharField(choices=[('authentic', 'Highly Authentic'), ('likely_real', 'Likely Real'), ('suspicious', 'Possibly Edited / Suspicious'), ('likely_fake', 'Likely AI Generated / Fake')], default='suspicious', max_length=20)),
                ('total_frames_analyzed', models.IntegerField(default=0)),
                ('frame_scores', models.JSONField(blank=True, default=list)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Scan',
                'verbose_name_plural': 'Video Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='tech-blue', max_length=30)),
                ('language', models.CharField(default='en', max_length=10)),
                ('cursor_style', models.CharField(default='default', max_length=20)),
                ('dark_mode', models.BooleanField(default=False)),
                ('total_scans', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_text', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('authenticity_score', models.FloatField(default=0.0)),
                ('classification', models.CharField(choices=[('authentic', 'Highly Authentic'), ('likely_real', 'Likely Real'), ('suspicious', 'Possibly Edited / Suspicious'), ('likely_fake', 'Likely AI Generated / Fake')], default='suspicious', max_length=20)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Scan',
                'verbose_name_plural': 'Text Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=core.models.upload_image_path)),
                ('original_filename', models.CharField(default='unknown', max_length=255)),
                ('authenticity_score', models.FloatField(default=0.0)),
                ('classification', models.CharField(choices=[('authentic', 'Highly Authentic'), ('likely_real', 'Likely Real'), ('suspicious', 'Possibly Edited / Suspicious'), ('likely_fake', 'Likely AI Generated / Fake')], default='suspicious', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('face_count', models.IntegerField(default=0)),
                ('has_exif', models.BooleanField(default=False)),
                ('exif_data', models.JSONField(blank=True, default=dict)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Scan',
                'verbose_name_plural': 'Image Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_sent_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to=core.models.upload_audio_path)),
                ('original_filename', models.CharField(default='unknown', max_length=255)),
                ('authenticity_score', models.FloatField(default=0.0)),
                ('classification', models.CharField(choices=[('authentic', 'Highly Authentic'), ('likely_real', 'Likely Real'), ('suspicious', 'Possibly Edited / Suspicious'), ('likely_fake', 'Likely AI Generated / Fake')], default='suspicious', max_length=20)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio Scan',
                'verbose_name_plural': 'Audio Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
