# Generated by Django 4.2.7 on 2026-03-14 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('text', 'Text')], max_length=10)),
                ('original_filename', models.CharField(blank=True, default='', max_length=500)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/%Y/%m/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('authenticity_score', models.IntegerField(default=0)),
                ('classification', models.CharField(choices=[('authentic', 'Highly Authentic'), ('likely_real', 'Likely Real'), ('suspicious', 'Suspicious'), ('likely_fake', 'Likely Fake')], default='suspicious', max_length=20)),
                ('explanation', models.TextField(blank=True, default='')),
                ('detailed_results', models.TextField(blank=True, default='{}')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('submitted_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Result',
                'verbose_name_plural': 'Scan Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
