# Generated by Django 4.2.16 on 2026-03-15 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('preferred_theme', models.CharField(default='dark', max_length=10)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('text', 'Text')], db_index=True, max_length=10)),
                ('original_filename', models.CharField(blank=True, default='', max_length=500)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/%Y/%m/%d/')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('submitted_text', models.TextField(blank=True, default='')),
                ('authenticity_score', models.FloatField(default=0.0)),
                ('classification', models.CharField(choices=[('highly_authentic', 'Highly Authentic'), ('likely_real', 'Likely Real'), ('suspicious', 'Suspicious'), ('likely_fake', 'Likely Fake')], default='suspicious', max_length=20)),
                ('real_vs_fake', models.CharField(default='Unknown', max_length=50)),
                ('explanation', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('detailed_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Result',
                'verbose_name_plural': 'Scan Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_scanre_user_id_a98b41_idx'), models.Index(fields=['scan_type', '-created_at'], name='core_scanre_scan_ty_e1c195_idx')],
            },
        ),
    ]
