# Generated by Django 4.2.7 on 2026-03-15 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('text', 'Text')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
