# Generated by Django 4.2.16 on 2026-03-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='classification',
            field=models.CharField(choices=[('highly_authentic', 'Highly Authentic'), ('likely_real', 'Likely Real'), ('suspicious', 'Suspicious'), ('likely_fake', 'Likely Fake'), ('ai_generated', 'AI Generated'), ('deepfake', 'DeepFake / Face Manipulation'), ('edited', 'Edited / Manipulated')], default='suspicious', max_length=100),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='real_vs_fake',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
