# Generated by Django 4.2.16 on 2026-03-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_scanresult_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='classification',
            field=models.CharField(choices=[('highly_authentic', 'Highly Authentic'), ('likely_real', 'Likely Real'), ('suspicious', 'Suspicious'), ('likely_fake', 'Likely Fake'), ('ai_generated', 'AI Generated'), ('deepfake', 'DeepFake'), ('edited', 'Edited')], default='suspicious', max_length=100),
        ),
    ]
