import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor, black, white, grey
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader


def build_image_scan_pdf(scan):
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Header
    p.setFillColor(HexColor("#0d6efd"))
    p.rect(0, height - 90, width, 90, fill=1, stroke=0)

    p.setFillColor(white)
    p.setFont("Helvetica-Bold", 22)
    p.drawString(40, height - 45, "Deep Fake Shield")
    p.setFont("Helvetica", 11)
    p.drawString(40, height - 63, "Image Authenticity Verification Report")

    y = height - 120
    p.setFillColor(black)

    p.setFont("Helvetica-Bold", 14)
    p.drawString(40, y, "Scan Summary")
    y -= 25

    p.setFont("Helvetica", 11)
    p.drawString(40, y, f"Filename: {scan.original_filename}")
    y -= 18
    p.drawString(40, y, f"Authenticity Score: {scan.authenticity_score:.1f}%")
    y -= 18
    p.drawString(40, y, f"Classification: {scan.classification}")
    y -= 18
    p.drawString(40, y, f"Faces Detected: {scan.face_count}")
    y -= 18
    p.drawString(40, y, f"EXIF Metadata: {'Present' if scan.has_exif else 'Missing'}")
    y -= 30

    p.setFont("Helvetica-Bold", 14)
    p.drawString(40, y, "Explanation")
    y -= 20

    p.setFont("Helvetica", 10)
    explanation_lines = (scan.explanation or "No explanation available.").split("\n")
    for line in explanation_lines[:15]:
        p.drawString(40, y, line[:100])
        y -= 14
        if y < 120:
            p.showPage()
            y = height - 60

    # Metrics
    if scan.analysis_details:
        y -= 10
        if y < 140:
            p.showPage()
            y = height - 60

        p.setFont("Helvetica-Bold", 14)
        p.drawString(40, y, "Key Metrics")
        y -= 20
        p.setFont("Helvetica", 10)

        for key, value in scan.analysis_details.items():
            if key in ['face_detection_image', 'face_locations']:
                continue
            p.drawString(40, y, f"{key}: {str(value)[:90]}")
            y -= 14
            if y < 100:
                p.showPage()
                y = height - 60

    # Add original image if available
    try:
        if scan.image and hasattr(scan.image, "path"):
            p.showPage()
            p.setFont("Helvetica-Bold", 16)
            p.drawString(40, height - 40, "Uploaded Image Preview")
            img = ImageReader(scan.image.path)
            p.drawImage(img, 40, 160, width=500, height=500, preserveAspectRatio=True, mask='auto')
    except Exception:
        pass

    p.setFont("Helvetica-Oblique", 9)
    p.setFillColor(grey)
    p.drawString(40, 30, "Generated by Deep Fake Shield")

    p.save()
    buffer.seek(0)
    return buffer